import { accessibleContests } from './accounts.js';
import { esc, csrf, input, table } from './views.js';
import { fail, id, text } from './bot-service.js';
import { maskCpf, maskPhone } from './privacy.js';
import { contest, fields } from './validation.js';
import { localToUtc } from './dates.js';
import { staffing } from './staffing.js';

const check=(label,name,value=true)=>`<label class="check"><input type="checkbox" name="${name}" value="1" ${value?'checked':''}>${label}</label>`;
const heading=(title,description='')=>`<div class="heading"><div><p class="eyebrow">AUTOMAÇÃO DE CONCURSOS</p><h1>${title}</h1><p>${description}</p></div></div>`;
export function mountBotAdmin(app,db,s,page,guard) {
  const groups=()=>db.prepare(`SELECT g.*,c.title,(SELECT code FROM bot_errors WHERE group_id=g.id ORDER BY created_at DESC,rowid DESC LIMIT 1) last_error FROM groups g JOIN contests c ON c.id=g.contest_id WHERE c.id IN (${accessibleContests()}) ORDER BY g.name`).all();
  const select=(label,name,rows,value)=>`<label>${label}<select name="${name}" required>${rows.map(r=>`<option value="${r.id}" ${value===r.id?'selected':''}>${esc(r.name||r.title)}</option>`).join('')}</select></label>`;
  const groupForm=(req,g={active:1,respond_command:1,respond_mention:1})=>`<form class="panel form-grid" method="post" action="/admin/groups${g.id?'/'+g.id:''}">${csrf(req.session.csrf)}${input('Nome do grupo','name',g.name)}${input('Instância Evolution','instance',g.instance)}${input('JID do grupo (@g.us)','remote_jid',g.remote_jid)}${input('Número do bot (DDI + número@s.whatsapp.net)','bot_jid',g.bot_jid)}${select('Concurso do grupo','contest_id',db.prepare(`SELECT id,title FROM contests WHERE id IN (${accessibleContests()}) ORDER BY title`).all(),g.contest_id)}<div>${check('Bot ativo','active',g.active)}${check('Responder a menção ou resposta ao bot','respond_mention',g.respond_mention)}${check('Responder a !duvida e !concurso','respond_command',g.respond_command)}</div><button>Salvar grupo</button></form>`;
  app.get('/admin/groups',(req,res)=>page(req,res,'Grupos',heading('Grupos do WhatsApp','Um concurso por grupo. Pause as respostas a qualquer momento.')+table(['Grupo','Concurso','Instância','Bot','Última mensagem (UTC)','Último erro',''],groups().map(g=>[esc(g.name),esc(g.title),esc(g.instance),g.active?'Ativo':'Pausado',esc(g.last_message_at||'—'),esc(g.last_error||'—'),`<a href="/admin/groups/${g.id}">Editar</a>`]))+'<h2>Novo grupo</h2>'+groupForm(req)));
  app.post('/admin/groups',(req,res)=>{const g=s.group(req.body);res.redirect(`/admin/groups/${g.id}`);});
  app.get('/admin/groups/:id',(req,res)=>{const g=s.getGroup(req.params.id);page(req,res,'Editar grupo',heading(esc(g.name))+`<p><a href="/l/${esc(g.code)}">Link de confirmação deste grupo ↗</a> · <a href="/admin/contests/${g.contest_id}/bot">Configurar FAQs e contexto</a></p>`+groupForm(req,g));});
  app.post('/admin/groups/:id',(req,res)=>{s.group(req.body,req.params.id);res.redirect('/admin/groups');});
  app.get('/admin/contests/:id/bot',(req,res)=>{
    const c=s.getContest(req.params.id),faqs=db.prepare('SELECT * FROM faqs WHERE contest_id=? ORDER BY sort_order,id').all(c.id);
    const faqForm=f=>`<form class="panel form-grid" method="post" action="/admin/contests/${c.id}/faqs${f.id?'/'+f.id:''}">${csrf(req.session.csrf)}${input('Pergunta','question',f.question,'text','maxlength="500"')}${input('Palavras-chave (separadas por espaço)','keywords',f.keywords||'','text','maxlength="500"')}<label class="wide">Resposta (até 500 caracteres)<textarea name="answer" required maxlength="500">${esc(f.answer)}</textarea></label>${input('Ordem','sort_order',f.sort_order||0,'number')}${check('Ativa','active',f.active??1)}<button>Salvar FAQ</button></form>${f.id?`<form method="post" action="/admin/faqs/${f.id}/delete">${csrf(req.session.csrf)}<button class="secondary">Excluir FAQ</button></form>`:''}`;
    page(req,res,'Configurar bot',heading(esc(c.title),'Informações utilizadas exclusivamente para responder dúvidas deste concurso.')+`<form class="panel" method="post"><input name="_csrf" type="hidden" value="${req.session.csrf}"><label>Link do edital<input type="url" name="edital_url" value="${esc(c.edital_url)}"></label><label>Início das inscrições (Brasília)<input type="datetime-local" name="registration_opens" value="${esc(c.registration_opens)}"></label><label>Contexto adicional para a IA<textarea rows="7" name="ai_context" maxlength="12000">${esc(c.ai_context)}</textarea></label><label>Mensagem quando faltar informação<textarea name="fallback" required maxlength="500">${esc(c.fallback)}</textarea></label><button>Salvar configurações</button></form><h2>Perguntas frequentes</h2>${faqs.map(faqForm).join('')}<h3>Adicionar pergunta</h3>${faqForm({})}`);
  });
  app.post('/admin/contests/:id/bot',(req,res)=>{
    const c=s.getContest(req.params.id),url=text(req.body.edital_url??'',2000,false),opens=text(req.body.registration_opens??'',30,false);
    if(url){let parsed;try{parsed=new URL(url);}catch{fail('Link do edital inválido.');}if(!['https:','http:'].includes(parsed.protocol))fail('Link do edital inválido.');}
    if(opens&&(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(opens)||opens>c.deadline))fail('Início das inscrições inválido.');
    db.prepare('UPDATE contests SET edital_url=?,registration_opens=?,registration_opens_utc=?,ai_context=?,fallback=? WHERE id=?').run(url,opens,opens?localToUtc(opens):null,text(req.body.ai_context??'',12000,false),text(req.body.fallback,500),c.id);
    s.audit('concurso.bot_atualizado',c.id);res.redirect(`/admin/contests/${c.id}/bot`);
  });
  app.post('/admin/contests/:id/faqs',(req,res)=>{s.faq(req.body,req.params.id);res.redirect(`/admin/contests/${req.params.id}/bot`);});
  app.post('/admin/contests/:id/faqs/:faq',(req,res)=>{s.faq(req.body,req.params.id,req.params.faq);res.redirect(`/admin/contests/${req.params.id}/bot`);});
  app.post('/admin/faqs/:id/delete',(req,res)=>{const f=db.prepare('SELECT * FROM faqs WHERE id=?').get(id(req.params.id));if(!f)fail('FAQ não encontrada.',404);db.prepare('DELETE FROM faqs WHERE id=?').run(f.id);s.audit('faq.excluida',f.id);res.redirect(`/admin/contests/${f.contest_id}/bot`);});
  const reminderForm=(req,r={})=>`<form class="panel form-grid" method="post" action="/admin/reminders${r.id?'/'+r.id:''}">${csrf(req.session.csrf)}${select('Grupo','group_id',groups(),r.group_id)}<label>Tipo<select name="type">${['INSCRICAO_ABERTA','INSCRICAO_ENCERRANDO','CONFIRMAR_CADASTRO','LEMBRETE_PROVA','MENSAGEM_PERSONALIZADA'].map(t=>`<option ${r.type===t?'selected':''}>${t}</option>`).join('')}</select></label><label class="wide">Mensagem<textarea name="message" rows="4" required maxlength="2000">${esc(r.message||'Quer trabalhar em {{nome_concurso}}? Cadastre-se pelo formulário: {{link_confirmacao}}. Não envie CPF no grupo.')}</textarea></label>${input('Enviar em (horário de Brasília)','execute_local',r.original_local,'datetime-local')}${input('Repetir a cada quantas horas? (0 = uma vez)','repeat_hours',r.repeat_hours||0,'number','min="0" max="8760"')}<label>Repetir até (obrigatório para repetições)<input type="datetime-local" name="repeat_until" value="${r.repeat_until?new Date(Date.parse(r.repeat_until)-10800000).toISOString().slice(0,16):''}"></label><small>Variáveis: {{nome_concurso}}, {{link_confirmacao}}, {{link_inscricao}}, {{data_fim}}, {{data_prova}}.</small><button>Salvar lembrete</button></form>`;
  app.get('/admin/reminders',(req,res)=>{
    s.recover();const rows=db.prepare(`SELECT r.*,g.name FROM reminders r JOIN groups g ON g.id=r.group_id WHERE r.contest_id IN (${accessibleContests()}) ORDER BY r.execute_at DESC LIMIT 200`).all();
    page(req,res,'Lembretes',heading('Lembretes programados','O n8n consulta a fila e executa os envios. Datas de execução exibidas em Brasília.')+table(['Grupo / tipo','Mensagem','Programado','Status / tentativas','Envio (UTC) / erro','Ações'],rows.map(r=>[`${esc(r.name)}<small>${esc(r.type)}</small>`,esc(r.message),esc(new Date(r.execute_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})),`${esc(r.status)} / ${r.attempts}`,`${esc(r.sent_at||'—')}<small>${esc(r.error||'')}</small>`,`${r.status==='PENDENTE'&&r.attempts===0?`<a href="/admin/reminders/${r.id}/edit">Editar</a>`:''}${['PENDENTE','ERRO'].includes(r.status)?`<form method="post" action="/admin/reminders/${r.id}/cancel">${csrf(req.session.csrf)}<button class="text">Cancelar</button></form>`:''}${r.status==='ERRO'&&r.attempts<3?`<form method="post" action="/admin/reminders/${r.id}/retry">${csrf(req.session.csrf)}<label class="check"><input type="checkbox" name="checked_delivery" value="yes" required> Conferi no provedor e não foi entregue</label><button class="secondary">Tentar novamente</button></form>`:''}`]))+'<h2>Novo lembrete</h2>'+reminderForm(req));
  });
  app.post('/admin/reminders',(req,res)=>{s.reminder(req.body);res.redirect('/admin/reminders');});
  app.get('/admin/reminders/:id/edit',(req,res)=>page(req,res,'Editar lembrete',heading('Editar lembrete')+reminderForm(req,s.getReminder(req.params.id))));
  app.post('/admin/reminders/:id',(req,res)=>{s.reminder(req.body,req.params.id);res.redirect('/admin/reminders');});
  for(const action of ['cancel','retry'])app.post(`/admin/reminders/:id/${action}`,(req,res)=>{if(action==='retry'&&req.body.checked_delivery!=='yes')fail('Confira a entrega antes de repetir.');s.transition(req.params.id,action);res.redirect('/admin/reminders');});
  app.get('/admin/history',(req,res)=>page(req,res,'Histórico',heading('Histórico do bot','Perguntas e respostas têm sequências de CPF removidas. Os eventos não incluem payloads ou credenciais.')+'<section class="panel"><h2>Mensagens recentes</h2>'+table(['Grupo','Pergunta','Resposta','Status','UTC'],db.prepare('SELECT m.*,g.name FROM bot_messages m LEFT JOIN groups g ON g.id=m.group_id ORDER BY m.created_at DESC,m.rowid DESC LIMIT 100').all().map(m=>[esc(m.name),esc(m.question),esc(m.response),esc(m.status),esc(m.created_at)]))+'</section><section class="panel"><h2>Erros</h2>'+table(['Workflow','Execução','Código','UTC'],db.prepare('SELECT * FROM bot_errors ORDER BY created_at DESC,rowid DESC LIMIT 100').all().map(e=>[esc(e.workflow),esc(e.execution_id),esc(e.code),esc(e.created_at)]))+'</section><section class="panel"><h2>Alterações administrativas</h2>'+table(['Responsável','Ação','Identificador','UTC'],db.prepare('SELECT * FROM audit ORDER BY created_at DESC,rowid DESC LIMIT 100').all().map(a=>[esc(a.actor),esc(a.action),esc(a.target),esc(a.created_at)]))+'</section>'));
  app.post('/admin/registrations/:id/delete',(req,res)=>{const result=db.prepare('DELETE FROM registrations WHERE id=?').run(id(req.params.id));if(!result.changes)fail('Participante não encontrado.',404);s.audit('participante.excluido',req.params.id);res.redirect('/admin/registrations');});

  // Administrative JSON API uses the same authenticated session and CSRF as the panel.
  app.use(['/api/grupos','/api/concursos','/api/faqs'],guard);
  app.get('/api/grupos',(req,res)=>res.json(groups()));
  app.get('/api/grupos/:id',(req,res)=>res.json(s.getGroup(req.params.id)));
  app.post('/api/grupos',(req,res)=>res.status(201).json(s.group(req.body)));
  app.put('/api/grupos/:id',(req,res)=>res.json(s.group(req.body,req.params.id)));
  app.get('/api/concursos/:id',(req,res)=>res.json(s.getContest(req.params.id)));
  app.post('/api/concursos',(req,res)=>{const c=contest(req.body);const r=db.prepare(`INSERT INTO contests(${fields.join(',')},owner_id) VALUES(${fields.map(()=>'?').join(',')},?) RETURNING id`).get(...fields.map(k=>c[k]),req.user.id);s.audit('concurso.criado',r.id);res.status(201).json(s.getContest(r.id));});
  app.put('/api/concursos/:id',(req,res)=>{const old=s.getContest(req.params.id),c=contest(req.body,old);db.prepare(`UPDATE contests SET ${fields.map(k=>`${k}=?`).join(',')} WHERE id=?`).run(...fields.map(k=>c[k]),old.id);s.audit('concurso.atualizado',old.id);res.json(s.getContest(old.id));});
  app.post('/api/concursos/:id/faqs',(req,res)=>res.status(201).json(s.faq(req.body,req.params.id)));
  app.put('/api/faqs/:id',(req,res)=>{const f=db.prepare('SELECT * FROM faqs WHERE id=?').get(id(req.params.id));if(!f)fail('FAQ não encontrada.',404);res.json(s.faq(req.body,f.contest_id,f.id));});
  app.delete('/api/faqs/:id',(req,res)=>{const result=db.prepare('DELETE FROM faqs WHERE id=?').run(id(req.params.id));if(!result.changes)fail('FAQ não encontrada.',404);s.audit('faq.excluida',req.params.id);res.json({ok:true});});
  app.post('/api/concursos/:id/lembretes',(req,res)=>{if(s.getGroup(req.body.group_id).contest_id!==id(req.params.id))fail('Grupo não pertence ao concurso.');res.status(201).json(s.reminder(req.body));});
  app.get('/api/concursos/:id/participantes',(req,res)=>{s.getContest(req.params.id);res.json(db.prepare('SELECT id,name,phone,cpf_full,cpf_final,pix_type,pix_key,source,created_at FROM registrations WHERE contest_id=? ORDER BY created_at DESC,rowid DESC LIMIT 500').all(id(req.params.id)).map(r=>({...r,phone:maskPhone(r.phone),cpf_final:undefined,cpf:r.cpf_full||null,confirmed:true,roles:staffing(db).assigned(r.id)})));});
}
