export const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const date = value => value ? esc(value.replace('T',' às ').replace(/^(\d{4})-(\d{2})-(\d{2})/, '$3/$2/$1')) : 'A definir';
export const money = value => Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export const csrf = token => `<input type="hidden" name="_csrf" value="${esc(token)}">`;
export function layout(title, body, {admin=false, user=null, token='', error=''} = {}) {
  const brand='<span class="mark">P</span> ponto de prova';
  const links=[['/admin','Visão geral'],['/admin/registrations','Colaboradores'],['/admin/groups','Grupos'],['/admin/reminders','Lembretes'],...(user?.role==='admin'?[['/admin/users','Usuários'],['/admin/history','Histórico'],['/admin/messages','WhatsApp']]:[])];
  const notice=error?`<div role="alert" class="alert">${esc(error)}</div>`:'';
  const header=admin?`<header class="bo-header"><a class="brand" href="/admin">${brand}<span class="brand-label">BACK-OFFICE</span></a><div class="account-info"><strong>${esc(user?.name)}</strong><span>${user?.role==='admin'?'Administrador':'Gestor de concursos'}</span></div></header>`:`<header><a class="brand" href="/">${brand}<span class="brand-label">CONCURSOS</span></a><nav><a href="/">Concursos</a><a href="/login">Área do organizador ↗</a></nav></header>`;
  const navigation=admin?`<aside class="bo-sidebar"><p class="eyebrow">GERENCIAMENTO</p><nav aria-label="Back-office">${links.map(([href,label])=>`<a href="${href}">${label}</a>`).join('')}<a href="/" target="_blank" rel="noopener">Portal público ↗</a></nav><form method="post" action="/logout">${csrf(token)}<button class="secondary">Sair da conta</button></form></aside>`:'';
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Ponto de Prova</title><link rel="stylesheet" href="/style.css"></head><body class="${admin?'backoffice':'public-site'}">${header}<div class="${admin?'bo-layout':''}">${navigation}<main>${notice}${body}</main></div><footer>Ponto de Prova <span>Informação organizada.</span></footer></body></html>`;
}
export function input(label,name,value='',type='text',extra='') {
  return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" required ${extra}></label>`;
}
export function contestForm(c={},token='') {
  return `<div class="heading"><div><p class="eyebrow">ORGANIZAÇÃO</p><h1>${c.id?'Editar':'Novo'} concurso</h1><p>Reúna as informações para quem vai trabalhar no concurso. O cadastro é gratuito.</p></div></div><form class="panel form-grid" method="post">${csrf(token)}${input('Nome do concurso','title',c.title)}${input('Banca / organizadora','organizer',c.organizer)}<p class="wide">${c.id?`<a href="/admin/contests/${esc(c.id)}/roles">Gerenciar cargos, períodos, valores e quantidades</a>`:'Após salvar o concurso, cadastre os cargos com seus períodos, valores e quantidades.'}</p>${input('Local da prova','location',c.location)}${input('Link de informações do concurso','official_url',c.official_url,'url')}${input('Fim dos cadastros','deadline',c.deadline,'datetime-local')}${input('Horário de chegada','arrival',c.arrival,'datetime-local')}${input('Início da prova','starts',c.starts,'datetime-local')}${input('Término da prova','ends',c.ends,'datetime-local')}<label class="wide">Documentos, requisitos e orientações<textarea name="notes" rows="5">${esc(c.notes)}</textarea></label><p class="wide muted">Datas e horários no fuso de Brasília. Caso a banca ainda não tenha definido o local, informe “A definir”.</p><div class="wide"><button>Salvar concurso</button> <a class="button secondary" href="/admin">Cancelar</a></div></form>`;
}
export function cards(contests,admin=false) {
  return contests.length?`<div class="cards">${contests.map(c=>`<article class="panel contest-card"><div class="card-top"><span class="badge">${c.active?'Cadastros abertos':'Cadastros finalizados'}</span></div><p class="eyebrow">${esc(c.organizer)}</p><h2>${esc(c.title)}</h2><p class="contest-roles">${esc(c.role)||'Cargos em definição'}</p><div class="facts"><div><small>CADASTRO</small><strong>Gratuito</strong></div><div><small>VAGAS PREVISTAS</small><strong>${c.vacancies}</strong></div></div><p class="muted">⌖ ${esc(c.location)}</p><p class="muted">Cadastros até ${date(c.deadline)}</p><a class="card-link" href="${admin?'/admin/contests/':'/concursos/'}${c.id}">${admin?'Gerenciar concurso':'Ver informações e cadastrar'} <span>↗</span></a></article>`).join('')}</div>`:'<div class="panel empty"><h2>Nenhum concurso por aqui ainda</h2><p>Os concursos cadastrados aparecerão neste espaço.</p></div>';
}
export function table(headers,rows,empty='Nenhum registro encontrado.') {
  return rows.length?`<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((x,i)=>`<td data-label="${esc(headers[i])}">${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:`<div class="empty muted">${empty}</div>`;
}
